import HeriverseNode from "../src/HeriverseGraph/HeriverseNode.js";

let cachedModalSteps = null;

export function createModalSteps(Heriverse) {
	return [
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC,
			title: "Nodo Stratigrafico",
			i18n_label: "STRATIGRAPHIC_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "Select",
					label: "Seleziona nodo stratigrafico",
					i18n_label: "STRATIGRAPHIC_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "TypeSelect",
					label: "Tipo",
					i18n_label: "TYPE_SELECTION_LABEL",
					type: "typeSelector",
					required: false,
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
					values: Object.values(HeriverseNode.STRATIGRAPHIC_TYPE),
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "Checklist",
					label: "Epoche",
					i18n_label: "EPOCHS_SELECTION_LABEL",
					type: "checklist",
					required: false,
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
					checklist_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.STRATIGRAPHIC + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.STRATIGRAPHIC,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.PROPERTY,
			title: "Nodo Proprietà",
			i18n_label: "PROPERTY_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PROPERTY + "Select",
					label: "Seleziona nodo Proprietà",
					i18n_label: "PROPERTY_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.PROPERTIES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PROPERTY + "Info",
					label: "Informazioni",
					i18n_label: "INFORMATION_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.PROPERTIES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PROPERTY + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.PROPERTIES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PROPERTY + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.PROPERTIES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PROPERTY + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.PROPERTIES,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.EXTRACTOR,
			title: "Nodo Estrattore",
			i18n_label: "EXTRACTOR_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EXTRACTOR + "Select",
					label: "Seleziona nodo Estrattore",
					i18n_label: "EXTRACTOR_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.EXTRACTORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EXTRACTOR + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EXTRACTORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EXTRACTOR + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.EXTRACTORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EXTRACTOR + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EXTRACTORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EXTRACTOR + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EXTRACTORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EXTRACTOR + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EXTRACTORS,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.COMBINER,
			title: "Nodo Combiner",
			i18n_label: "COMBINER_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.COMBINER + "Select",
					label: "Seleziona nodo Combiner",
					i18n_label: "COMBINER_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.COMBINERS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.COMBINER + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.COMBINERS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.COMBINER + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.COMBINERS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.COMBINER + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.COMBINERS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.COMBINER + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.COMBINERS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.COMBINER + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.COMBINERS,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.TIME_BRANCH_GROUP,
			title: "Nodo TimeBranchGroup",
			i18n_label: "TIMEBRANCHGROUP_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.TIME_BRANCH_GROUP + "Select",
					label: "Seleziona nodo TimeBranchGroup",
					i18n_label: "TIMEBRANCHGROUP_NODE_SELECT",
					type: "select",
					element_type: "time_branch_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.TIME_BRANCH_GROUP + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "time_branch_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.TIME_BRANCH_GROUP + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "time_branch_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.TIME_BRANCH_GROUP + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: "time_branch_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.TIME_BRANCH_GROUP + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: "time_branch_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.TIME_BRANCH_GROUP + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: "time_branch_group",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL,
			title: "Nodo RM",
			i18n_label: "RM_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL + "Select",
					label: "Seleziona nodo RM",
					i18n_label: "RM_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODELS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODELS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODELS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODELS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODELS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODELS,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_DOC,
			title: "Nodo RM doc",
			i18n_label: "RM_DOC_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_DOC + "Select",
					label: "Seleziona nodo RM Doc",
					i18n_label: "RM_DOC_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_DOC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_DOC + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_DOC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_DOC + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_DOC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_DOC + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_DOC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_DOC + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_DOC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_DOC + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_DOC,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_SF,
			title: "Nodo RM SF",
			i18n_label: "RM_SF_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_SF + "Select",
					label: "Seleziona nodo RM SF",
					i18n_label: "RM_SF_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_SF + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_SF + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_SF + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_SF + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.REPRESENTATION_MODEL_SF + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.REPRESENTATION_MODEL_SF,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH,
			title: "Nodo Epoca",
			i18n_label: "EPOCH_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "Select",
					label: "Seleziona nodo Epoca",
					i18n_label: "EPOCH_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "StartTime",
					label: "Inizio Epoca",
					i18n_label: "START_EPOCH_LABEL",
					type: "number",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "EndTime",
					label: "Fine Epoca",
					i18n_label: "END_EPOCH_LABEL",
					type: "number",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "Color",
					label: "Colore associato",
					i18n_label: "COLOR_LABEL",
					type: "color",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "MinY",
					label: "Y Minima",
					i18n_label: "MIN_Y_LABEL",
					type: "number",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "MaxY",
					label: "Y Massima",
					i18n_label: "MAX_Y_LABEL",
					type: "number",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EPOCH + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.EPOCHS,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA,
			title: "Nodo Paradata",
			i18n_label: "PARADATA_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA + "Select",
					label: "Seleziona nodo Paradata",
					i18n_label: "PARADATA_NODE_SELECT",
					type: "select",
					element_type: "paradata",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "paradata",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "paradata",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: "paradata",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: "paradata",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: "paradata",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA_GROUP,
			title: "Nodo ParadataGroup",
			i18n_label: "PARADATAGROUP_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA_GROUP + "Select",
					label: "Seleziona nodo ParadataGroup",
					i18n_label: "PARADATAGROUP_NODE_SELECT",
					type: "select",
					element_type: "parada_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA_GROUP + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "parada_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA_GROUP + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "parada_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA_GROUP + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: "parada_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA_GROUP + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: "parada_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.PARADATA_GROUP + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: "parada_group",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.DOCUMENT,
			title: "Nodo Documento",
			i18n_label: "DOCUMENT_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.DOCUMENT + "Select",
					label: "Seleziona nodo Documento",
					i18n_label: "DOCUMENT_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.DOCUMENTS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.DOCUMENT + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.DOCUMENTS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.DOCUMENT + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.DOCUMENTS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.DOCUMENT + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.DOCUMENTS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.DOCUMENT + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.DOCUMENTS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.DOCUMENT + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.DOCUMENTS,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.ACTIVITY_GROUP,
			title: "Nodo ActivityGroup",
			i18n_label: "ACTIVITYGROUP_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.ACTIVITY_GROUP + "Select",
					label: "Seleziona nodo ActivityGroup",
					i18n_label: "ACTIVITYGROUP_NODE_SELECT",
					type: "select",
					element_type: "activity_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.ACTIVITY_GROUP + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "activity_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.ACTIVITY_GROUP + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "activity_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.ACTIVITY_GROUP + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: "activity_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.ACTIVITY_GROUP + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: "activity_group",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.ACTIVITY_GROUP + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: "activity_group",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.GRAPH,
			title: "Nodo Graph",
			i18n_label: "GRAPH_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GRAPH + "Select",
					label: "Seleziona nodo Graph",
					i18n_label: "GRAPH_NODE_SELECT",
					type: "select",
					element_type: "graph",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GRAPH + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "graph",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GRAPH + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "graph",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GRAPH + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: "graph",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GRAPH + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: "graph",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GRAPH + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: "graph",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.GEO_POSITION,
			title: "Nodo GeoPosition",
			i18n_label: "GEO_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GEO_POSITION + "Select",
					label: "Seleziona nodo GeoPosition",
					i18n_label: "GEO_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.GEO,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GEO_POSITION + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.GEO,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GEO_POSITION + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.GEO,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GEO_POSITION + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.GEO,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GEO_POSITION + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.GEO,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.GEO_POSITION + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.GEO,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.SPECIAL_FIND_UNIT,
			title: "Nodo SF",
			i18n_label: "SF_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SPECIAL_FIND_UNIT + "Select",
					label: "Seleziona nodo SF",
					i18n_label: "SF_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.STRATIGRAPHIC_TYPE.SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SPECIAL_FIND_UNIT + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.STRATIGRAPHIC_TYPE.SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SPECIAL_FIND_UNIT + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.STRATIGRAPHIC_TYPE.SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SPECIAL_FIND_UNIT + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.STRATIGRAPHIC_TYPE.SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SPECIAL_FIND_UNIT + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.STRATIGRAPHIC_TYPE.SF,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SPECIAL_FIND_UNIT + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.STRATIGRAPHIC_TYPE.SF,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.NODE,
			title: "Nodo",
			i18n_label: "NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.NODE + "Select",
					label: "Seleziona nodo",
					i18n_label: "NODE_SELECT",
					type: "select",
					element_type: "node",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.NODE + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "node",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.NODE + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "node",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.NODE + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: "node",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.NODE + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: "node",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.NODE + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: "node",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.SEMANTIC_SHAPE,
			title: "Nodo Semantic Shape",
			i18n_label: "SEMANTIC_SHAPE_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SEMANTIC_SHAPE + "Select",
					label: "Seleziona nodo Semantic Shape",
					i18n_label: "SEMANTIC_SHAPE_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.SEMANTIC_SHAPES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SEMANTIC_SHAPE + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.SEMANTIC_SHAPES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SEMANTIC_SHAPE + "Relate",
					label: "Seleziona nodo stratigrafico",
					i18n_label: "STRATIGRAPHIC_NODE_SELECT",
					type: "nodeSelector",
					required: false,
					element_type: HeriverseNode.TYPE.SEMANTIC_SHAPES,
					valuesType: HeriverseNode.NODE_TYPE.STRATIGRAPHIC,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SEMANTIC_SHAPE + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.SEMANTIC_SHAPES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SEMANTIC_SHAPE + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.SEMANTIC_SHAPES,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.SEMANTIC_SHAPE + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.SEMANTIC_SHAPES,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.LICENSE,
			title: "Nodo Licenza",
			i18n_label: "LICENSE_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LICENSE + "Select",
					label: "Seleziona nodo Licenza",
					i18n_label: "LICENSE_NODE_SELECT",
					type: "select",
					element_type: "license",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LICENSE + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "license",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LICENSE + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "license",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.EMBARGO,
			title: "Nodo Embargo",
			i18n_label: "EMBARGO_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EMBARGO + "Select",
					label: "Seleziona nodo Embargo",
					i18n_label: "EMBARGO_NODE_SELECT",
					type: "select",
					element_type: "embargo",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EMBARGO + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: "embargo",
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.EMBARGO + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: "embargo",
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.LINK,
			title: "Nodo Link",
			i18n_label: "LINK_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "Select",
					label: "Seleziona nodo Link",
					i18n_label: "LINK_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.LINKS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.LINKS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.LINKS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "TypeSelect",
					label: "Tipo",
					i18n_label: "TYPE_SELECTION_LABEL",
					type: "typeSelector",
					required: false,
					element_type: HeriverseNode.TYPE.LINKS,
					values: ["External Link", "3d_model", "image", "document"],
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "Files",
					label: "File Locali",
					i18n_label: "LOCAL_FILE_LABEL",
					type: "file",
					multiple: true,
					required: false,
					accept: "",
					element_type: HeriverseNode.TYPE.LINKS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "FileText",
					label: "File Remoto",
					i18n_label: "REMOTE_FILE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.LINKS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "License",
					label: "Licenza",
					i18n_label: "LICENSE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.LINKS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "Authors",
					label: "Autori (usare le virgole come separatori per gli autori)",
					i18n_label: "AUTHORS_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.LINKS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.LINK + "Embargo",
					label: "Data di Embargo",
					i18n_label: "EMBARGO_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.LINKS,
				},
			],
		},
		{
			node_type: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR,
			title: "Nodo Link",
			i18n_label: "LINK_NODE_TITLE",
			fields: [
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "Select",
					label: "Seleziona nodo Link",
					i18n_label: "LINK_NODE_SELECT",
					type: "select",
					element_type: HeriverseNode.TYPE.AUTHORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "Name",
					label: "Nome",
					i18n_label: "NAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.AUTHORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "Surname",
					label: "Surname",
					i18n_label: "SURNAME_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.AUTHORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "Description",
					label: "Descrizione",
					i18n_label: "DESCRIPTION_LABEL",
					type: "textarea",
					required: false,
					element_type: HeriverseNode.TYPE.AUTHORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "TypeSelect",
					label: "Tipo",
					i18n_label: "TYPE_SELECTION_LABEL",
					type: "typeSelector",
					required: false,
					element_type: HeriverseNode.TYPE.AUTHORS,
					values: ["author", "author_ai"],
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "Orcid",
					label: "Orcid",
					i18n_label: "ORCID_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.AUTHORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "Model",
					label: "Model",
					i18n_label: "MODEL_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.AUTHORS,
				},
				{
					id: Heriverse.CONNECTION_RULES_NODETYPES.AUTHOR + "PromptRefer",
					label: "Prompt Reference",
					i18n_label: "PROMPT_REFERENCE_LABEL",
					type: "text",
					required: false,
					element_type: HeriverseNode.TYPE.AUTHORS,
				},
			],
		},
	];
}

export function getModalSteps() {
	const Heriverse = globalThis.Heriverse;

	if (!Heriverse) {
		throw new Error("Heriverse non è ancora disponibile.");
	}

	if (!Heriverse.CONNECTION_RULES_NODETYPES) {
		throw new Error("Heriverse.CONNECTION_RULES_NODETYPES non è ancora inizializzato.");
	}

	if (!cachedModalSteps) {
		cachedModalSteps = createModalSteps(Heriverse);
	}

	return cachedModalSteps;
}
